### ISSUE TITLE
I'm wondering what meaning and affect of column 'status'？

### ISSUE THREAD

**Issue by Veitor** [yii2mod/yii2-settings#22]
There are two methods `activate` and `deactivate`, but i don't known what meaning and affect of them. are they just activate and deactivate a setting? I can remove one setting item which is not used any more from table and code, so i don't need to use `activate` or `deactive` methods.

**Comment by ihorchepurnyi** [comment]
Hi, I use this column on production, sometimes I need the setting only on production and staging environment.
