### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by paskuale75** [yii2mod/yii2-settings#28]
There's a way to define default values if an attribute is null?

**Comment by ihorchepurnyi** [comment]
Hi, no.
You can override the Setting component and change logic for `set` function.

**Comment by paskuale75** [comment]
Ok thanks.

**Comment by paskuale75** [comment]
Uhm, I've a customForm model example, I try to override Setting component (function set) but when that function called?

**Comment by ihorchepurnyi** [comment]
https://github.com/yii2mod/yii2-settings/blob/master/actions/SettingsAction.php#L155

**Comment by paskuale75** [comment]
Thanks for reply but here we are in the phase of saving attributes, I would like to set a kind of initialization of the attributes, for example, the color attribute if it is never saved must return the red. starting from [here](https://github.com/yii2mod/yii2-settings#manage-custom-settings)

**Comment by ihorchepurnyi** [comment]
Maybe you can use `default` value validator in your model

**Comment by ihorchepurnyi** [comment]
https://www.yiiframework.com/doc/guide/2.0/en/tutorial-core-validators#default

**Comment by paskuale75** [comment]
I've already tried that but the validation works when an attribute is saved with no value in it, maybe I can solve it with a migration.
