### ISSUE TITLE
Migration m161109_104201_rename_setting_table.php fails

### ISSUE THREAD

**Issue by BBrunekreeft** [yii2mod/yii2-settings#3]
Migration m161109_104201_rename_setting_table.php fails with error message:

> PHP Fatal error:  Class 'app\components\Migration' not found in /path/vendor/yii2mod/yii2-settings/migrations/m161109_104201_rename_setting_table.php on line 5
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'app\components\Migration' not found'

Line 3 says: 
`use app\components\Migration;`

Shouldn't this be 
`use yii\db\Migration;`

**Comment by ihorchepurnyi** [comment]
Thanks
Fixed by commit 2f19fa50e22a46afa3400c8259ee5ba044980775
