### ISSUE TITLE
add description column

### ISSUE THREAD

**Issue by masihfathi** [yii2mod/yii2-settings#8]
thanks for your extension.
is it good idea to add "description" column to setting table and models?(just for further information for key and value)

**Comment by ihorchepurnyi** [comment]
Hi, it's a good idea. I'm going to do this today.

**Comment by masihfathi** [comment]
Thanks for your efforts

**Comment by ihorchepurnyi** [comment]
I merged new pull request for this feature. Now, you can update your package and execute the new migration for `description` column by the following command:
```bash
$ php yii migrate --migrationPath=@vendor/yii2mod/yii2-settings/migrations
```
